// Class generated by AI.

package fr.piricraft.piricraftJobs.managers;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import fr.piricraft.piricraftJobs.PiricraftJobs;
import fr.piricraft.piricraftJobs.models.JobProfile;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

public class JobsDatabaseManager {

    private Connection connection;
    private final PiricraftJobs plugin;
    private final Map<UUID, JobProfile> profileCache = new ConcurrentHashMap<>();
    private final Gson gson = new GsonBuilder().create();

    public JobsDatabaseManager(PiricraftJobs plugin, Connection connection) {
        this.plugin = plugin;
        this.connection = connection;
    }

    public void initDatabase() {
        String query = "CREATE TABLE IF NOT EXISTS piricraft_jobs ("
                + "uuid VARCHAR(36) PRIMARY KEY, "
                + "active_job VARCHAR(32), "
                + "data_json TEXT"
                + ");";

        try (PreparedStatement stmt = connection.prepareStatement(query)) {
            stmt.executeUpdate();
        } catch (SQLException e) {
            plugin.getLogger().severe("Erreur lors de l'initialisation de la table piricraft_jobs : " + e.getMessage());
        }
    }

    public CompletableFuture<JobProfile> loadProfileAsync(UUID uuid) {
        return CompletableFuture.supplyAsync(() -> {
            String query = "SELECT data_json FROM piricraft_jobs WHERE uuid = ?;";

            try (PreparedStatement stmt = connection.prepareStatement(query)) {
                stmt.setString(1, uuid.toString());
                ResultSet rs = stmt.executeQuery();

                if (rs.next()) {
                    String json = rs.getString("data_json");
                    JobProfile profile = gson.fromJson(json, JobProfile.class);
                    profileCache.put(uuid, profile);
                    return profile;
                }
            } catch (SQLException e) {
                plugin.getLogger().severe("Erreur lors du chargement du profil pour " + uuid + " : " + e.getMessage());
            }

            JobProfile newProfile = new JobProfile(uuid);
            profileCache.put(uuid, newProfile);
            return newProfile;
        });
    }

    public CompletableFuture<Void> saveProfileAsync(JobProfile profile) {
        return CompletableFuture.runAsync(() -> {
            String query = "REPLACE INTO piricraft_jobs (uuid, active_job, data_json) VALUES (?, ?, ?);";

            try (PreparedStatement stmt = connection.prepareStatement(query)) {
                stmt.setString(1, profile.getPlayerUuid().toString());
                stmt.setString(2, profile.getActiveJob() != null ? profile.getActiveJob().name() : null);
                stmt.setString(3, gson.toJson(profile));
                stmt.executeUpdate();
            } catch (SQLException e) {
                plugin.getLogger().severe("Erreur lors de la sauvegarde du profil pour " + profile.getPlayerUuid() + " : " + e.getMessage());
            }
        });
    }

    public void unloadProfile(UUID uuid) {
        JobProfile profile = profileCache.get(uuid);
        if (profile != null) {
            saveProfileAsync(profile).thenRun(() -> profileCache.remove(uuid));
        }
    }

    public JobProfile getProfileFromCache(UUID uuid) {
        return profileCache.get(uuid);
    }
}