name: PiricraftJobs
description: Jobs plugin for Pirircraft.
version: '${version}'

main: fr.piricraft.piricraftJobs.PiricraftJobs
api-version: '26.2'
load: POSTWORLD
depend: [PiricraftCore]

authors: [ Lepipassier ]
website: https://github.com/PiricraftDev/Piricraft-Jobs

commands:
  jobs:
    description: Ouvre le menu des jobs.